#!/usr/bin/perl
use strict;

my $num_pairs = 30;

print <<EOS;
//##### This file is generated by $0 #####

EOS

## JSON_VALUE* ##
print <<EOS;
#define JSON_VALUE_2(Name_1_, Type_1_, Name_2_, Type_2_) \\
  JSON_VALUE(Name_1_, BCL_JOIN(Type_1_)) \\
  JSON_VALUE(Name_2_, BCL_JOIN(Type_2_))
EOS
my $a1 = 'Name_1_, Type_1_, Name_2_, Type_2_';
my $a2 = 'Name_2_, BCL_JOIN(Type_2_)';
for (my $i = 3; $i <= $num_pairs; $i++) {
  $a1 .= ", Name_${i}_, Type_${i}_";
  $a2 .= ", Name_${i}_, BCL_JOIN(Type_${i}_)";
  print <<EOS;
#define JSON_VALUE_${i}($a1) \\
  JSON_VALUE(Name_1_, BCL_JOIN(Type_1_)) \\
  JSON_VALUE_@{[$i-1]}($a2)
EOS
}

## JSON_ACCESS_* ##
print <<EOS;

#define JSON_ACCESS_2(Object_, Name_1_, Name_2_) \\
  JSON_ACCESS(Object_, Name_1_) \\
  JSON_ACCESS(Object_, Name_2_)
EOS
$a1 = 'Name_2_';
for (my $i = 3; $i <= $num_pairs; $i++) {
  $a1 .= ", Name_${i}_";
  print <<EOS;
#define JSON_ACCESS_$i(Object_, Name_1_, $a1) \\
  JSON_ACCESS(Object_, Name_1_) \\
  JSON_ACCESS_@{[$i-1]}(Object_, $a1)
EOS
}

## JSON_OBJECT_PAIR_* ##
print <<EOS;

#define JSON_OBJECT_PAIR(Object_, Name_, Type_) \\
  JSON_VALUE(Name_, BCL_JOIN(Type_)) \\
  JSON_OBJECT(Object_, Name_) \\
  JSON_ACCESS(Object_, Name_)
EOS
$a1 = 'Object_, Name_1_, Type_1_';
$a2 = 'Object_, Name_1_';
my $a3 = 'Name_1_, BCL_JOIN(Type_1_)';
for (my $i = 2; $i <= $num_pairs; $i++) {
  $a1 .= ", Name_${i}_, Type_${i}_";
  $a2 .= ", Name_${i}_";
  $a3 .= ", Name_${i}_, BCL_JOIN(Type_${i}_)";
  print <<EOS;
#define JSON_OBJECT_PAIR_$i($a1) \\
  JSON_VALUE_$i($a3) \\
  JSON_OBJECT($a2) \\
  JSON_ACCESS_$i($a2)
EOS
}

## JSON_OBJECT_ROOT_PAIR_* ##
print <<EOS;

#define JSON_OBJECT_ROOT_PAIR(Object_, Name_, Type_) \\
  JSON_VALUE(Name_, Type_) \\
  JSON_OBJECT_ROOT(Object_, Name_) \\
  JSON_ACCESS(Object_, Name_)
EOS
$a1 = 'Object_, Name_1_, Type_1_';
$a2 = 'Name_1_, BCL_JOIN(Type_1_)';
$a3 = 'Object_, Name_1_';
for (my $i = 2; $i <= $num_pairs; $i++) {
  $a1 .= ", Name_${i}_, Type_${i}_";
  $a2 .= ", Name_${i}_, BCL_JOIN(Type_${i}_)";
  $a3 .= ", Name_${i}_";
  print <<EOS;
#define JSON_OBJECT_ROOT_PAIR_$i($a1) \\
  JSON_VALUE_$i($a2) \\
  JSON_OBJECT_ROOT($a3) \\
  JSON_ACCESS_$i($a3)
EOS
}
print "\n";

